package:
  name: istio-envoy-1.23
  version: 1.23.3
  epoch: 0
  description: Envoy with additional Istio plugins (wasm, telemetry, etc)
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 20
    memory: 50Gi
  dependencies:
    provides:
      - istio-envoy=${{package.full-version}}

environment:
  contents:
    packages:
      # We don't use automake/autoconf directly, but the Bazel rule uses them
      - autoconf
      - automake
      - bash
      - bazel-6
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang~15
      - cmake
      - coreutils
      - git
      - libtool
      - llvm-libcxx-15
      - llvm-libcxx-15-dev
      - llvm-lld-15
      - llvm15
      - llvm15-cmake-default
      - llvm15-dev
      - llvm15-tools
      - openjdk-11
      - openssl-dev
      - patch
      - python3-dev
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/proxy
      tag: ${{package.version}}
      expected-commit: cbd889517ed13455bf2d88facc5685d958eb54a6

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      mkdir -p .cache/bazel/_bazel_root

      bazel build --verbose_failures -c opt envoy

      mkdir -p ${{targets.destdir}}/usr/bin/
      mv bazel-bin/envoy ${{targets.destdir}}/usr/bin/envoy

      # We no longer need this cache dir, which has some writable files.
      rm -rf .cache/bazel

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # link /usr/bin/envoy /usr/local/bin/envoy because Istio proxy-agent expects Envoy here
          # See https://github.com/istio/istio/blob/1.18.0/pkg/config/constants/constants.go#L59-L60
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/envoy ${{targets.subpkgdir}}/usr/local/bin/envoy
    dependencies:
      provides:
        - istio-envoy-compat=${{package.full-version}}

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/proxy
    tag-filter-prefix: 1.23.
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        envoy --version
        envoy --help
